version: '2.4'

services: 

  postgres:
    image: postgres:11
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=group_service
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 4s
      retries: 3

networks:
  backend: